void test_state_initialization(int *total_tests, int *fails);
void test_quarter_rounds      (int *total_tests, int *fails);
void test_apply_chacha_block  (int *total_tests, int *fails);
void test_serialization       (int *total_tests, int *fails);
void test_chacha_encryption   (int *total_tests, int *fails);
void test_poly1305_key_gen    (int *total_tests, int *fails);
void test_aead_encryption     (int *total_tests, int *fails);
void test_aead_decryption     (int *total_tests, int *fails);
void test_poly1305_tag_gen    (int *total_tests, int *fails);
void test_poly2133_tag_gen    (int *total_tests, int *fails);